#!/bin/bash

FULL=━
EMPTY=┄
C0="#161616"
C1="#161616"
C2="#78a9ff"
C3="#ee5396"
C4="#08bdba"
C5="#ffab91"
C6="#673ab7"
C7="#be95ff"
C8="#78a9ff"

draw() {
	perc=$1
	size=$2
	inc=$((perc * size / 100))
	out=
	for v in $(seq 0 $((size - 1))); do
		test "$v" -le "$inc" &&
			out="${out}#[fg=$C1]${FULL}" ||
			out="${out}#[fg=$C6]${EMPTY}"
	done
	echo "$out"
}
temp() {
	builtin type -P "sensors" &>/dev/null || exit
	t=$(sensors | awk '/Core\ 0/ {gsub(/\+/,"",$3); gsub(/\..+/,"",$3)    ; print $3}')
	tc=$C0
	if [ $((t <= 50)) ]; then
		tc=$C2
	elif [ $((t >= 75)) ]; then
		tc=$C3
	fi
	echo " #[fg=$tc]$t°c"
}
bat() {
	BATPATH=/sys/class/power_supply/BAT0
	STATUS=$BATPATH/status
	BAT_FULL=$BATPATH/charge_full
	BAT_NOW=$BATPATH/charge_now
	bf=$(cat $BAT_FULL)
	bn=$(cat $BAT_NOW)
	bp=$((100 * bn / bf))
	stat=$(cat $STATUS)
	case $stat in
	Full)
		st="="
		;;
	Discharging)
		st="-"
		;;
	Charging)
		st="+"
		;;
	esac
	test "$bp" -lt 10 &&
		bc=$C3 ||
		bc=$C1
	echo "$st#[fg=$bc]$bp""%"
}
cpu() {
	CPU_USE=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
	printf "%.0f" "$CPU_USE"
}
ram() {
	free | awk '/Mem:/ {print int($3/$2 * 100.0)}'
}
disk() {
	df -h | grep '/$' | tr -s ' ' | cut -d ' ' -f5 | sed 's/%//'
}
vpn() {
	pgrep 'vpn/|openvpn/|openconnect' >/dev/null 2>&1 && echo "#[bg=$C8]#[fg=$C7]▓▒░#[fg=0]" || echo "#[bg=$C8]#[fg=$C7]▓▒░#[fg=0]"
}
clock() {
	mtime=$(date +'%H:%M')
	echo "#[fg=$C0]#[bg=$C7] $mtime ▒░"
}
front() {
	echo "#[bg=$C7]#[fg=0]▓▒░"
}
separator() {
	echo "#[bg=$C9]#[fg=$C4]░▒#[bg=$C9]#[fg=$C9]▓"
}
CPU_INFO=$(cpu)
RAM_INFO=$(ram)
DISK_INFO=$(disk)
echo "$(front)" "#[fg=0] ${RAM_INFO}%" "$(draw "$RAM_INFO" 4)" "#[fg=0]  ${CPU_INFO}%" "$(draw "$CPU_INFO" 4)" "#[fg=0]󰽄 ${DISK_INFO}%" "$(draw "${DISK_INFO}" 4)" "$(clock)"
